imports:
    - { resource: parameters.yml }

framework:
    secret: test_blah
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: "%kernel.debug%"
    form: true
    csrf_protection: true
    validation: { enable_annotations: true }
    default_locale: en
    trusted_proxies: ~
    session: ~

doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8
    orm:
        auto_generate_proxy_classes: %kernel.debug%
        entity_managers:
            default:
                auto_mapping: false
                mappings:
                    test_behat:
                        type: xml
                        dir: %kernel.root_dir%/../features/bootstrap/Bundle/Resources/config/doctrine
                        prefix: Rezzza\Bundle\Entity
                        is_bundle: false
